### ISSUE TITLE
Spaced Repetition history reset

### ISSUE THREAD

**Issue by cr7mmsa** [hannesfrank/awesome-remnote#11]
Hello, It would be very perfect if there's a plugin that do the same function of reschedule in Anki. I think this is a very important feature that should be added. and thank you and have a nice day

**Comment by WildGenius** [comment]
[Experimental snippet by @hannesfrank](https://forum.remnote.io/t/quick-setting-to-reset-spaced-repetition-history-of-a-single-flashcard/1184/14) posted on the forums.

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.sentidofront, @CarlosAlbertoReyesV, @heresyrj, @leohuqi, @masknugget, @DeiseFreire, @decster, @Tulip4attoo, @resolvedtechnologies, @errorrik, @SiavashDST, @dxv2k, @SorenLittle, @tangjicheng46, @yrachid, @kad3nce, @DLBob, @gunandrose4u, @sl2782087, @johnxie

**Comment by hannesfrank** [comment]
As of 1.14.15 (Beta) flashcard history management is built-in. You can reset practice history, record extra practice sessions and set the next practice date.
