### ISSUE TITLE
can you help guide me in making cards from a paste buffer?

### ISSUE THREAD

**Issue by bksubhuti** [hannesfrank/awesome-remnote#25]
My email is bksubhuti using the gmail server

I have a project which exports keyword and definition flashcards for a reading application.  It also takes the context from where it was taken.

I can export to anki without any problems because anki takes html and our data is html.
remnote is another story because it is MD and I think not totally MD.

My biggest issue is having multiple lines within a single rem.  I don't know how to do that.

I want  h3 for the word
### word ###
context sentence >> (start of card)
definition 1
definition 2
definition 3

I understand I cannot make colors and many of the details are not going to be expandable.
However, my main problem is understanding how to emulate "shift enter" in a String pasted to the clipboard buffer.
My problem is all new lines are new rems.

something like above.. Here is a photo of the flash cards internal to the project .
I don't want to have the burden of making a flash card program and management.  So I want to export.  I support remnote, but anki is easier.  Ironically, anki is more difficult for end-users.  So I wish to support remnote.

front:
![image](https://github.com/hannesfrank/awesome-remnote/assets/18184280/fe06eca9-b252-4737-96e8-3bdea057bbaa)
back:
![image](https://github.com/hannesfrank/awesome-remnote/assets/18184280/495e7de2-6af9-4c1a-8aa1-f9b2b65e1176)

**Comment by bksubhuti** [comment]
For instance.. i sort of have markdown like this with output in code..
The only thing I need help with is to have multiple lines on a single rem.  and have the answers be multiple lines as well.


```

### pathaviṃ
idha, bhikkhave, assutavā puthujjano ariyānaṃ adassāvī ariyadhammassa akovido ariyadhamme avinīto, sappurisānaṃ adassāvī sappurisadhammassa akovido sappurisadhamme avinīto – **pathaviṃ** pathavito sañjānāti, **pathaviṃ** pathavito saññatvā **pathaviṃ** maññati, pathaviyā maññati, pathavito maññati, **pathaviṃ** meti maññati, **pathaviṃ** abhinandati.>>
- pathavī 1: fem. earth; world [√path + avī] ✓
- pathavī 2: fem. earth; ground [√path + avī] ✓
- pathavī 3: fem. ground; land; country [√path + avī] ✓
```

which might look like this


### pathaviṃ
idha, bhikkhave, assutavā puthujjano ariyānaṃ adassāvī ariyadhammassa akovido ariyadhamme avinīto, sappurisānaṃ adassāvī sappurisadhammassa akovido sappurisadhamme avinīto – **pathaviṃ** pathavito sañjānāti, **pathaviṃ** pathavito saññatvā **pathaviṃ** maññati, pathaviyā maññati, pathavito maññati, **pathaviṃ** meti maññati, **pathaviṃ** abhinandati.>>
- pathavī 1: fem. earth; world [√path + avī] ✓
- pathavī 2: fem. earth; ground [√path + avī] ✓
- pathavī 3: fem. ground; land; country [√path + avī] ✓

**Comment by bksubhuti** [comment]
https://discord.com/channels/689979930804617224/719288461231652984/1130479268963549265

**Comment by hannesfrank** [comment]
Yeah, Discord is the right place to discuss a solution!

**Comment by bksubhuti** [comment]
i didn't really get any answers on that medium.  In the end.. i just "settled" for making an md file without cards.
